

# Reciving trainerroom list of training
GET http://localhost:4000/api/user/traininglist?trainingQttSortingType=asc&totalMoneySortingType=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTk0MzUwNywiZXhwIjoxNjg5OTQ0NDA3fQ.fYFoqatP9ZtErbZSdIeNna5FtK_S6eHOlmLS2BGTYfg
###

# Delete friend from user
DELETE http://localhost:4000/api/client/friend/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0OCwiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg2NTE2MzYsImV4cCI6MTY5ODY1MjUzNn0.Jo97Tihj4SDP0E1EwnbNdqNnBfWL_34Of3gluWXYJaE
###

# Get friends

GET http://localhost:4000/api/user/friend/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNlcDNvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5MjQxNzI4LCJleHAiOjE2ODkyNDI2Mjh9.sDX2LFqqYNg2cNF2lwm_jDtg6weNxcJ8AAYn-kO4ZWU.
###
# Check training
GET http://localhost:4000/api/user/training/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6InRyYWluZXJAZ21haWwuY3dtIiwidXNlclJvbGUiOiJ0cmFpbmVyIiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5OTIzNzU3LCJleHAiOjE2ODk5MjQ2NTd9.bzpEsxjr_aec4lOcDuAL2tCEPuw3t1Mits9pk5RN7ZI
###

# Use training

DELETE  http://localhost:4000/api/user/training/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNlcDNvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5MzUxNDQ5LCJleHAiOjE2ODkzNTIzNDl9.BPGR4L4ju3T5YwZO3ZGvCylGSS20BLno4IkKFakZdZo
###


# Post feedback

POST http://localhost:4000/api/user/feedback HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNlcDNvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5MzM4NjA2LCJleHAiOjE2ODkzMzk1MDZ9.HgqisKyPPia2U5qIAq_0vvC8EVs9yWFpsZjFklZAI4c
Content-Type: application/json

{
  "trainingId": 7,
  "rating": 1,
  "text": "это было блестящще, блестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящщеблестящще"
}

###
# Order training
POST http://localhost:4000/api/user/order HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6InRyYWluZXJAZ21haWwuY3dtIiwidXNlclJvbGUiOiJ0cmFpbmVyIiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5OTIwOTU1LCJleHAiOjE2ODk5MjE4NTV9.IiwjXbxJwMpXFBLFXQpsV1CtyJJRTMChWYymGijOB6I
Content-Type: application/json

{
  "typeOfOrder": "абонемент",
  "trainingId": 7,
  "price": 10,
  "qtt": 100,
  "typeOfPayment": "visa"
}
###
# Order personal training
POST http://localhost:4000/api/user/personalorder/66 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjY3LCJlbWFpbCI6ImNsaWVudG1hc2hhQGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6Ik1hc2ggQ2xpZW50IiwiaWF0IjoxNjkyNzIwOTQxLCJleHAiOjE2OTI3MjE4NDF9.qo62eJMXXDI6RBUQs2QbmGAVP3OHxXIbR9kJrHMylVc

###

# Get personal order
GET http://localhost:4000/api/user/personalorder/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5NDA1MTc5LCJleHAiOjE2ODk0MDYwNzl9.blbzGDBPExepNx2oQUMMF2YdQMrR9qKK79TKYQd5EjI
###

# confirm personal training
PATCH http://localhost:4000/api/client/personal-order?orderId=208&newStatus=принят HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwNCwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NTY2ODgsImV4cCI6MTY5ODc1NzU4OH0.TEeZ5iybu3JPcQxpBVgdXnXP4gF1wxi2lbbkchmT0qY
###

# Reject the personal training
PATCH http://localhost:4000/api/client/personal-order?orderId=205&newStatus=отклонён HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMSwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NTQ4NjksImV4cCI6MTY5ODc1NTc2OX0.UM2wO_VjrDdwGEc42Tup0oaK5yr4WnwPW5HUd8g_93Q
###

# Reciving trainerroom list of training
GET http://localhost:4000/api/user/traininglist?trainingQttSortingType=asc&totalMoneySortingType=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTk0MzUwNywiZXhwIjoxNjg5OTQ0NDA3fQ.fYFoqatP9ZtErbZSdIeNna5FtK_S6eHOlmLS2BGTYfg
###

# # Reciving recomendations userroom list of trainining
# GET http://localhost:4000/api/user/recomendations HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTk0MzUwNywiZXhwIjoxNjg5OTQ0NDA3fQ.fYFoqatP9ZtErbZSdIeNna5FtK_S6eHOlmLS2BGTYfg
# {
#   "typesOfTraining": [],
#   "timeOfTraining": 1,
#   "levelOfExperience": "",
#   "caloryLosingPlanTotal": 1000
# }
# ###
